# Project-wide Gradle settings.

# JVM Arguments
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# AndroidX & Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Version Kotlin
android.kotlinVersion=1.8.10

# Version Flipper
FLIPPER_VERSION=0.182.0

# React Native & Hermes Settings
hermesEnabled=true
expo.jsEngine=hermes
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64