# Project-wide Gradle settings.

# IDE (Android Studio) users:
# Settings specified in this file apply to all Gradle builds in the project.
# For more information on how to configure your build environment visit:
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# When configured, Gradle will run in incubating parallel mode.
# Use this option to compile multi-project builds in parallel.
# org.gradle.parallel=true

# AndroidX package structure to make it clearer which packages are bundled with the
# Android support library, rather than being part of the SDK.
android.useAndroidX=true
android.enableJetifier=true

# Force Kotlin 1.8.10 pour éviter l'échec de compilation expo-splash-screen
android.kotlinVersion=1.8.10

# Version Flipper requise par le build native React Native
FLIPPER_VERSION=0.182.0